ci(core): fix ci.

diff --git a/apps/bot/Dockerfile b/apps/bot/Dockerfile
--- a/apps/bot/Dockerfile
+++ b/apps/bot/Dockerfile
@@ -2,8 +2,8 @@ ARG VERSION=null
 
 FROM node:18-alpine AS base
 WORKDIR /app
-RUN apk update
-RUN apk add --no-cache libc6-compat
+RUN apk update \
+    apk add --no-cache libc6-compat net-tools
 
 # ----------------- Setup a turbo partial monorepo -----------------
 FROM base AS builder
@@ -29,6 +29,8 @@ RUN yarn turbo run build
 # ----------------- Run the production image -----------------
 FROM base AS runner
 LABEL version=$VERSION
+ENV PORT=$PORT
+
 RUN corepack enable
 
 RUN addgroup --system --gid 1001 bot
@@ -38,6 +40,9 @@ USER bot
 COPY --from=installer --chown=bot:bot /app .
 COPY apps/bot/src/proto/*.proto apps/bot/dist/proto
 
-EXPOSE 3002
+EXPOSE $PORT
+
+# HEALTHCHECK --interval=30s --timeout=10s --start-period=5s --retries=3 \
+#   CMD netstat -ltn | grep -c "$PORT" || exit 1
 
 ENTRYPOINT [ "sh", "-c", "node apps/bot/dist/main" ]
